services:
  # acme-companion:
  #   image: nginxproxy/acme-companion
  #   container_name: acme-companion
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./certs:/etc/nginx/certs
  #     - ./html:/usr/share/nginx/html
  #   environment:
  #     - DEFAULT_EMAIL=${DEFAULT_EMAIL_ACME}
  #     - NGINX_PROXY_CONTAINER=nginx-proxy
  #   depends_on:
  #     - nginx-proxy
  #   networks:
  #     - webproxy

  nginx-proxy:
    restart: always
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html
    environment:
      - TRUST_DOWNSTREAM_PROXY=false
    networks:
      - webproxy
      - app-network

  backend:
    environment:
      - DJANGO_SETTINGS_MODULE=videoflix.settings
      - VIRTUAL_HOST=${VIRTUAL_HOST_BACKEND}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST_BACKEND}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
      - ENVIRONMENT=production
      - RUN_MIGRATIONS=true
    # command: /app/compose/run_backend.sh

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      # - ./frontend_html:/usr/share/nginx/html
      - ./backend/media:/usr/share/nginx/html/media
      - ./backend/staticfiles:/usr/share/nginx/html/static
      - ./nginx-config:/etc/nginx/conf.d
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_FRONTEND}
      - LETSENCRYPT_HOST=${LETSENCRYPT_HOST_FRONTEND}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
    networks:
      - app-network

networks:
  webproxy:
    external: true
  app-network:
    driver: bridge
