# docker-compose.override.yml
version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev # Entwicklungs-Dockerfile verwenden
    environment:
      - DJANGO_SETTINGS_MODULE=videoflix.settings # Development Settings
      - DEBUG=True
    volumes:
      - ./backend:/app # Lokale Ordner für Live-Coding mounten
    ports:
      - "8000:8000" # Freigabe des Ports für den Entwicklungsserver

  frontend:
    build:
      context: ./frontend # Pfad zu deinem Angular-Projekt
      dockerfile: Dockerfile.dev # Verwende das Entwicklungs-Dockerfile
    ports:
      - "4200:4200" # Exponiere den Port 4200 für Angular
    volumes:
      - ./frontend:/usr/src/app # Binde das lokale Angular-Verzeichnis
      - ./backend/media:/usr/src/media
      - node_modules:/usr/src/app/node_modules
      # - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Ermöglicht besseres Dateiwatching in Docker
      - NGINX_HOST=localhost

  nginx-media:
    image: nginx:latest
    container_name: nginx-media
    volumes:
      - ./backend/media:/usr/share/nginx/html/media  # Mount des Media-Verzeichnisses
      - ./nginx-config/nginx-media.conf:/etc/nginx/conf.d/default.conf  # Nginx-Konfiguration
    ports:
      - "8081:80"  # Nginx auf Port 8081, um Medien auszuliefern
    restart: unless-stopped

  postgres:
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CFfRdzBewPEGG
    ports:
      - "5432:5432"

  redis:
    ports:
      - 6379:6379

volumes:
  node_modules:
