# docker-compose.override.yml
version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - DJANGO_SETTINGS_MODULE=videoflix.settings
      - DEBUG=True
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app # Binde das lokale Angular-Verzeichnis
      - ./backend/media:/usr/src/media
      - node_modules:/usr/src/app/node_modules
      # - /usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true # Ermöglicht besseres Dateiwatching in Docker
      - NGINX_HOST=localhost

  # nginx-media:
  #   restart: unless-stopped
  #   image: nginx:latest
  #   container_name: nginx-media
  #   volumes:
  #     # - ./backend/media:/usr/share/nginx/html/media
  #     - ./nginx-config/nginx-media.conf:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "8081:4200"

  postgres:
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  redis:
    ports:
      - 6379:6379

volumes:
  node_modules:
