services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - DJANGO_SETTINGS_MODULE=videoflix.settings
      - DEBUG=True
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/usr/src/app
      - ./backend/media:/usr/src/media
      - node_modules:/usr/src/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NGINX_HOST=localhost

  postgres:
    ports:
      - "5432:5432"

  redis:
    ports:
      - 6379:6379

volumes:
  node_modules:
