# Generated by Django 5.1.1 on 2024-09-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_video_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumbnails'),
        ),
    ]
