# Generated by Django 5.1.1 on 2024-10-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0004_video_hls_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='hls_path',
        ),
        migrations.AddField(
            model_name='video',
            name='video_1280p',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_480p',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
        migrations.AddField(
            model_name='video',
            name='video_720p',
            field=models.FileField(blank=True, null=True, upload_to='videos'),
        ),
    ]
