# Generated by Django 5.1.1 on 2024-10-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0009_alter_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
