# Generated by Django 5.1.1 on 2024-10-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0010_video_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
    ]
