# Generated by Django 5.1.1 on 2024-11-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0014_alter_video_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='teaser_file',
            field=models.FileField(blank=True, null=True, upload_to='teasers'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
