# Generated by Django 5.1.1 on 2024-11-10 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0015_video_teaser_file_alter_video_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='progress',
        ),
    ]
