name: Build and Deploy Angular App

on:
  push:
    branches:
    - main # oder den Branch anpassen, den du verwenden möchtest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '17' # Passe die Node.js-Version nach Bedarf an

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      working-directory: ./frontend # Ordnername anpassen
      run: npm install

    - name: Build Angular App
      working-directory: ./frontend # Ordnername anpassen
      run: ng build --configuration production

    - name: Deploy to Server
      env:
        SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        # SSH-Schlüssel für die Sitzung konfigurieren
        mkdir -p ~/.ssh
        echo "$SSH_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # IP oder Domain deines Servers, und Pfad anpassen
        SERVER_USER="root"  # Hier deinen SSH-Benutzernamen einfügen
        SERVER_IP="188.245.97.4"  # Hier deine Server-IP einfügen
        SERVER_PATH="/test/gitactions"  # Zielverzeichnis auf deinem Server

        # Kopiere die gebauten Dateien auf den Server
        scp -r ./frontend/dist/frontend_videoflix/* $SERVER_USER@$SERVER_IP:$SERVER_PATH

        # Optionale Bereinigung des SSH-Keys
        rm -f ~/.ssh/id_rsa
