# Generated by Django 5.1.1 on 2024-10-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0003_video_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hls_path',
            field=models.FileField(blank=True, null=True, upload_to='hls'),
        ),
    ]
