# Generated by Django 5.1.1 on 2024-10-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0006_remove_video_video_1280p_remove_video_video_480p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hls_playlist',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
